// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
  comment_id,
  user_id,
  location_id,
  text,
  status
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  'active'
)
RETURNING comment_id, user_id, location_id, text, created_at, updated_at, status
`

type CreateCommentParams struct {
	CommentID  uuid.UUID `json:"comment_id"`
	UserID     uuid.UUID `json:"user_id"`
	LocationID uuid.UUID `json:"location_id"`
	Text       string    `json:"text"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.CommentID,
		arg.UserID,
		arg.LocationID,
		arg.Text,
	)
	var i Comment
	err := row.Scan(
		&i.CommentID,
		&i.UserID,
		&i.LocationID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
UPDATE comments
SET
  status = 'deleted',
  updated_at = NOW()
WHERE comment_id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, commentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteComment, commentID)
	return err
}

const getCommentsByLocation = `-- name: GetCommentsByLocation :many
SELECT comment_id, user_id, location_id, text, created_at, updated_at, status
FROM comments
WHERE location_id = $1
  AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) GetCommentsByLocation(ctx context.Context, locationID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.CommentID,
			&i.UserID,
			&i.LocationID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hideComment = `-- name: HideComment :exec
UPDATE comments
SET
  status = 'hidden',
  updated_at = NOW()
WHERE comment_id = $1
`

func (q *Queries) HideComment(ctx context.Context, commentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, hideComment, commentID)
	return err
}
