// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getNearbyLocations = `-- name: GetNearbyLocations :many
SELECT location_id, name, description, geom
FROM locations
WHERE ST_DWithin(
  geom,
  ST_Transform(
    ST_SetSRID(ST_MakePoint($1, $2), 4326),
    25832
  ),
  $3
)
ORDER BY created_at DESC
`

type GetNearbyLocationsParams struct {
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	StDwithin     interface{} `json:"st_dwithin"`
}

type GetNearbyLocationsRow struct {
	LocationID  uuid.UUID      `json:"location_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Geom        interface{}    `json:"geom"`
}

func (q *Queries) GetNearbyLocations(ctx context.Context, arg GetNearbyLocationsParams) ([]GetNearbyLocationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getNearbyLocations, arg.StMakepoint, arg.StMakepoint_2, arg.StDwithin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNearbyLocationsRow
	for rows.Next() {
		var i GetNearbyLocationsRow
		if err := rows.Scan(
			&i.LocationID,
			&i.Name,
			&i.Description,
			&i.Geom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
