// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: locations.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (
  location_id,
  name,
  description,
  geom,
  address,
  location_type,
  opening_hours,
  status,
  creator_user_id
)
VALUES (
  $1, $2, $3,
  ST_SetSRID(ST_MakePoint($4, $5), 4326),
  $6, $7, $8,
  $9,
  $10
)
RETURNING location_id, name, description, geom, address, location_type, opening_hours, created_at, updated_at, status, creator_user_id, average_rating
`

type CreateLocationParams struct {
	LocationID    uuid.UUID             `json:"location_id"`
	Name          string                `json:"name"`
	Description   sql.NullString        `json:"description"`
	StMakepoint   interface{}           `json:"st_makepoint"`
	StMakepoint_2 interface{}           `json:"st_makepoint_2"`
	Address       sql.NullString        `json:"address"`
	LocationType  sql.NullString        `json:"location_type"`
	OpeningHours  pqtype.NullRawMessage `json:"opening_hours"`
	Status        sql.NullString        `json:"status"`
	CreatorUserID uuid.UUID             `json:"creator_user_id"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation,
		arg.LocationID,
		arg.Name,
		arg.Description,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.Address,
		arg.LocationType,
		arg.OpeningHours,
		arg.Status,
		arg.CreatorUserID,
	)
	var i Location
	err := row.Scan(
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.Geom,
		&i.Address,
		&i.LocationType,
		&i.OpeningHours,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.CreatorUserID,
		&i.AverageRating,
	)
	return i, err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT location_id, name, description, geom, address, location_type, opening_hours, created_at, updated_at, status, creator_user_id, average_rating
FROM locations
WHERE location_id = $1
`

func (q *Queries) GetLocationByID(ctx context.Context, locationID uuid.UUID) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocationByID, locationID)
	var i Location
	err := row.Scan(
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.Geom,
		&i.Address,
		&i.LocationType,
		&i.OpeningHours,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.CreatorUserID,
		&i.AverageRating,
	)
	return i, err
}

const getLocationsInBounds = `-- name: GetLocationsInBounds :many
SELECT
  location_id,
  name,
  ST_X(geom) AS lng,
  ST_Y(geom) AS lat
FROM locations
WHERE geom && ST_MakeEnvelope($1, $2, $3, $4, 4326)
  AND status = 'active'
`

type GetLocationsInBoundsParams struct {
	StMakeenvelope   interface{} `json:"st_makeenvelope"`
	StMakeenvelope_2 interface{} `json:"st_makeenvelope_2"`
	StMakeenvelope_3 interface{} `json:"st_makeenvelope_3"`
	StMakeenvelope_4 interface{} `json:"st_makeenvelope_4"`
}

type GetLocationsInBoundsRow struct {
	LocationID uuid.UUID   `json:"location_id"`
	Name       string      `json:"name"`
	Lng        interface{} `json:"lng"`
	Lat        interface{} `json:"lat"`
}

func (q *Queries) GetLocationsInBounds(ctx context.Context, arg GetLocationsInBoundsParams) ([]GetLocationsInBoundsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLocationsInBounds,
		arg.StMakeenvelope,
		arg.StMakeenvelope_2,
		arg.StMakeenvelope_3,
		arg.StMakeenvelope_4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLocationsInBoundsRow
	for rows.Next() {
		var i GetLocationsInBoundsRow
		if err := rows.Scan(
			&i.LocationID,
			&i.Name,
			&i.Lng,
			&i.Lat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNearbyLocations = `-- name: GetNearbyLocations :many
SELECT location_id, name, description, geom
FROM locations
WHERE ST_DWithin(
  geom::geography,
  ST_SetSRID(ST_MakePoint($1, $2), 4326)::geography,
  $3
)
ORDER BY created_at DESC
`

type GetNearbyLocationsParams struct {
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	StDwithin     interface{} `json:"st_dwithin"`
}

type GetNearbyLocationsRow struct {
	LocationID  uuid.UUID      `json:"location_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Geom        interface{}    `json:"geom"`
}

func (q *Queries) GetNearbyLocations(ctx context.Context, arg GetNearbyLocationsParams) ([]GetNearbyLocationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getNearbyLocations, arg.StMakepoint, arg.StMakepoint_2, arg.StDwithin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNearbyLocationsRow
	for rows.Next() {
		var i GetNearbyLocationsRow
		if err := rows.Scan(
			&i.LocationID,
			&i.Name,
			&i.Description,
			&i.Geom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLocations = `-- name: SearchLocations :many
SELECT location_id, name, description, geom, address, location_type, opening_hours, created_at, updated_at, status, creator_user_id, average_rating
FROM locations
WHERE name ILIKE '%' || $1 || '%'
  AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) SearchLocations(ctx context.Context, dollar_1 sql.NullString) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, searchLocations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.LocationID,
			&i.Name,
			&i.Description,
			&i.Geom,
			&i.Address,
			&i.LocationType,
			&i.OpeningHours,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.CreatorUserID,
			&i.AverageRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET
  name = $2,
  description = $3,
  address = $4,
  location_type = $5,
  status = $6,
  updated_at = NOW()
WHERE location_id = $1
RETURNING location_id, name, description, geom, address, location_type, opening_hours, created_at, updated_at, status, creator_user_id, average_rating
`

type UpdateLocationParams struct {
	LocationID   uuid.UUID      `json:"location_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Address      sql.NullString `json:"address"`
	LocationType sql.NullString `json:"location_type"`
	Status       sql.NullString `json:"status"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, updateLocation,
		arg.LocationID,
		arg.Name,
		arg.Description,
		arg.Address,
		arg.LocationType,
		arg.Status,
	)
	var i Location
	err := row.Scan(
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.Geom,
		&i.Address,
		&i.LocationType,
		&i.OpeningHours,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.CreatorUserID,
		&i.AverageRating,
	)
	return i, err
}
