// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getModerationQueue = `-- name: GetModerationQueue :many
SELECT queue_id, location_id, comment_id, content_type, reason, added_at, status, moderator_id
FROM moderation_queue
WHERE status = 'pending'
ORDER BY added_at ASC
`

func (q *Queries) GetModerationQueue(ctx context.Context) ([]ModerationQueue, error) {
	rows, err := q.db.QueryContext(ctx, getModerationQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationQueue
	for rows.Next() {
		var i ModerationQueue
		if err := rows.Scan(
			&i.QueueID,
			&i.LocationID,
			&i.CommentID,
			&i.ContentType,
			&i.Reason,
			&i.AddedAt,
			&i.Status,
			&i.ModeratorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewModeration = `-- name: ReviewModeration :exec
UPDATE moderation_queue
SET
  status = $2,
  moderator_id = $3
WHERE queue_id = $1
`

type ReviewModerationParams struct {
	QueueID     uuid.UUID      `json:"queue_id"`
	Status      sql.NullString `json:"status"`
	ModeratorID uuid.NullUUID  `json:"moderator_id"`
}

func (q *Queries) ReviewModeration(ctx context.Context, arg ReviewModerationParams) error {
	_, err := q.db.ExecContext(ctx, reviewModeration, arg.QueueID, arg.Status, arg.ModeratorID)
	return err
}
