// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Location struct {
	LocationID    uuid.UUID             `json:"location_id"`
	Name          string                `json:"name"`
	Description   sql.NullString        `json:"description"`
	Geom          interface{}           `json:"geom"`
	Address       sql.NullString        `json:"address"`
	LocationType  sql.NullString        `json:"location_type"`
	OpeningHours  pqtype.NullRawMessage `json:"opening_hours"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
	Status        string                `json:"status"`
	CreatorUserID uuid.UUID             `json:"creator_user_id"`
}

type LocationTag struct {
	LocationID uuid.UUID `json:"location_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

type Tag struct {
	TagID    uuid.UUID `json:"tag_id"`
	TagName  string    `json:"tag_name"`
	Category string    `json:"category"`
}

type User struct {
	UserID       uuid.UUID `json:"user_id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	IsModerator  bool      `json:"is_moderator"`
	IsDeleted    bool      `json:"is_deleted"`
}
