// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Comment struct {
	CommentID  uuid.UUID      `json:"comment_id"`
	UserID     uuid.UUID      `json:"user_id"`
	LocationID uuid.UUID      `json:"location_id"`
	Text       string         `json:"text"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	Status     sql.NullString `json:"status"`
}

type FediverseContent struct {
	ContentID   uuid.UUID      `json:"content_id"`
	LocationID  uuid.UUID      `json:"location_id"`
	ExternalID  sql.NullString `json:"external_id"`
	ContentType sql.NullString `json:"content_type"`
	Text        sql.NullString `json:"text"`
	PublishedAt sql.NullTime   `json:"published_at"`
	SourceUrl   sql.NullString `json:"source_url"`
}

type Location struct {
	LocationID    uuid.UUID             `json:"location_id"`
	Name          string                `json:"name"`
	Description   sql.NullString        `json:"description"`
	Geom          interface{}           `json:"geom"`
	Address       sql.NullString        `json:"address"`
	LocationType  sql.NullString        `json:"location_type"`
	OpeningHours  pqtype.NullRawMessage `json:"opening_hours"`
	CreatedAt     sql.NullTime          `json:"created_at"`
	UpdatedAt     sql.NullTime          `json:"updated_at"`
	Status        sql.NullString        `json:"status"`
	CreatorUserID uuid.UUID             `json:"creator_user_id"`
	AverageRating sql.NullFloat64       `json:"average_rating"`
}

type LocationTag struct {
	LocationID uuid.UUID `json:"location_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

type ModerationQueue struct {
	QueueID     uuid.UUID      `json:"queue_id"`
	LocationID  uuid.NullUUID  `json:"location_id"`
	CommentID   uuid.NullUUID  `json:"comment_id"`
	ContentType sql.NullString `json:"content_type"`
	Reason      sql.NullString `json:"reason"`
	AddedAt     sql.NullTime   `json:"added_at"`
	Status      sql.NullString `json:"status"`
	ModeratorID uuid.NullUUID  `json:"moderator_id"`
}

type Moderator struct {
	ModeratorID uuid.UUID    `json:"moderator_id"`
	UserID      uuid.UUID    `json:"user_id"`
	ApprovedAt  sql.NullTime `json:"approved_at"`
}

type Rating struct {
	RatingID   uuid.UUID     `json:"rating_id"`
	UserID     uuid.UUID     `json:"user_id"`
	LocationID uuid.UUID     `json:"location_id"`
	Score      sql.NullInt32 `json:"score"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

type Report struct {
	ReportID   uuid.UUID      `json:"report_id"`
	UserID     uuid.UUID      `json:"user_id"`
	LocationID uuid.NullUUID  `json:"location_id"`
	CommentID  uuid.NullUUID  `json:"comment_id"`
	Reason     string         `json:"reason"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	Status     sql.NullString `json:"status"`
}

type Tag struct {
	TagID    uuid.UUID `json:"tag_id"`
	TagName  string    `json:"tag_name"`
	Category string    `json:"category"`
}

type User struct {
	UserID       uuid.UUID    `json:"user_id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	IsModerator  sql.NullBool `json:"is_moderator"`
	IsDeleted    sql.NullBool `json:"is_deleted"`
}
