// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetNearbyLocations(ctx context.Context, arg GetNearbyLocationsParams) ([]GetNearbyLocationsRow, error)
	GetUser(ctx context.Context, userID uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
