// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetLocationByID(ctx context.Context, locationID uuid.UUID) (Location, error)
	GetLocationsInBounds(ctx context.Context, arg GetLocationsInBoundsParams) ([]GetLocationsInBoundsRow, error)
	GetNearbyLocations(ctx context.Context, arg GetNearbyLocationsParams) ([]GetNearbyLocationsRow, error)
	GetUser(ctx context.Context, userID uuid.UUID) (User, error)
	GetUserIDByEmail(ctx context.Context, email string) (GetUserIDByEmailRow, error)
	ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error)
	SearchLocations(ctx context.Context, dollar_1 sql.NullString) ([]Location, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
}

var _ Querier = (*Queries)(nil)
