// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratings.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRating = `-- name: CreateRating :one
INSERT INTO ratings (
  rating_id,
  user_id,
  location_id,
  score
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING rating_id, user_id, location_id, score, created_at
`

type CreateRatingParams struct {
	RatingID   uuid.UUID     `json:"rating_id"`
	UserID     uuid.UUID     `json:"user_id"`
	LocationID uuid.UUID     `json:"location_id"`
	Score      sql.NullInt32 `json:"score"`
}

func (q *Queries) CreateRating(ctx context.Context, arg CreateRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, createRating,
		arg.RatingID,
		arg.UserID,
		arg.LocationID,
		arg.Score,
	)
	var i Rating
	err := row.Scan(
		&i.RatingID,
		&i.UserID,
		&i.LocationID,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}

const getRatingsByLocation = `-- name: GetRatingsByLocation :many
SELECT rating_id, user_id, location_id, score, created_at
FROM ratings
WHERE location_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRatingsByLocation(ctx context.Context, locationID uuid.UUID) ([]Rating, error) {
	rows, err := q.db.QueryContext(ctx, getRatingsByLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rating
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.RatingID,
			&i.UserID,
			&i.LocationID,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocationAverageRating = `-- name: UpdateLocationAverageRating :exec
UPDATE locations
SET average_rating = (
  SELECT AVG(ratings.score)::float
  FROM ratings
  WHERE ratings.location_id = locations.location_id
)
WHERE locations.location_id = $1
`

func (q *Queries) UpdateLocationAverageRating(ctx context.Context, locationID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLocationAverageRating, locationID)
	return err
}
