// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getReports = `-- name: GetReports :many
SELECT report_id, user_id, location_id, comment_id, reason, created_at, status
FROM reports
ORDER BY created_at DESC
`

func (q *Queries) GetReports(ctx context.Context) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, getReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ReportID,
			&i.UserID,
			&i.LocationID,
			&i.CommentID,
			&i.Reason,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportComment = `-- name: ReportComment :one
INSERT INTO reports (
  report_id,
  user_id,
  comment_id,
  reason,
  status
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  'pending'
)
RETURNING report_id, user_id, location_id, comment_id, reason, created_at, status
`

type ReportCommentParams struct {
	ReportID  uuid.UUID     `json:"report_id"`
	UserID    uuid.UUID     `json:"user_id"`
	CommentID uuid.NullUUID `json:"comment_id"`
	Reason    string        `json:"reason"`
}

func (q *Queries) ReportComment(ctx context.Context, arg ReportCommentParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, reportComment,
		arg.ReportID,
		arg.UserID,
		arg.CommentID,
		arg.Reason,
	)
	var i Report
	err := row.Scan(
		&i.ReportID,
		&i.UserID,
		&i.LocationID,
		&i.CommentID,
		&i.Reason,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const reportLocation = `-- name: ReportLocation :one
INSERT INTO reports (
  report_id,
  user_id,
  location_id,
  reason,
  status
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  'pending'
)
RETURNING report_id, user_id, location_id, comment_id, reason, created_at, status
`

type ReportLocationParams struct {
	ReportID   uuid.UUID     `json:"report_id"`
	UserID     uuid.UUID     `json:"user_id"`
	LocationID uuid.NullUUID `json:"location_id"`
	Reason     string        `json:"reason"`
}

func (q *Queries) ReportLocation(ctx context.Context, arg ReportLocationParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, reportLocation,
		arg.ReportID,
		arg.UserID,
		arg.LocationID,
		arg.Reason,
	)
	var i Report
	err := row.Scan(
		&i.ReportID,
		&i.UserID,
		&i.LocationID,
		&i.CommentID,
		&i.Reason,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}
