// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  user_id,
  username,
  email,
  password_hash,
  created_at,
  is_moderator,
  is_deleted
)
VALUES (
  $1, $2, $3, $4, NOW(), false, false
)
RETURNING user_id, username, email, password_hash, created_at, is_moderator, is_deleted
`

type CreateUserParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsModerator,
		&i.IsDeleted,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT user_id, username, email, password_hash, created_at, is_moderator, is_deleted
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsModerator,
		&i.IsDeleted,
	)
	return i, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT user_id, email, password_hash
FROM users
WHERE email = $1
`

type GetUserIDByEmailRow struct {
	UserID       uuid.UUID `json:"user_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (GetUserIDByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByEmail, email)
	var i GetUserIDByEmailRow
	err := row.Scan(&i.UserID, &i.Email, &i.PasswordHash)
	return i, err
}
